pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script:
    cmake -E make_directory build
  displayName: Creating build directory
- script:
    cmake -E chdir build cmake ../cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  displayName: Configuring
- script:
    cmake --build build --target cctools -- -j 4
  displayName: Building
