#ifndef CCPORT_MACH_ARM_THREAD_STATUS_H_
#define CCPORT_MACH_ARM_THREAD_STATUS_H_

#ifdef THREAD_STATE_NONE
#undef THREAD_STATE_NONE
#endif /* THREAD_STATE_NONE */

#ifdef VALID_THREAD_STATE_FLAVOR
#undef VALID_THREAD_STATE_FLAVOR
#endif /* VALID_THREAD_STATE_FLAVOR */

#ifdef MACHINE_THREAD_STATE
#undef MACHINE_THREAD_STATE
#endif /* MACHINE_THREAD_STATE */

#ifdef MACHINE_THREAD_STATE_COUNT
#undef MACHINE_THREAD_STATE_COUNT
#endif /* MACHINE_THREAD_STATE_COUNT */

#include_next <mach/arm/thread_status.h>

#endif /* CCPORT_MACH_ARM_THREAD_STATUS_H_ */
